### ISSUE TITLE
edge-workbook for IoT Edge 1.0.10

### ISSUE THREAD

**Issue by ReneHezser** [veyalla/iotedge-labs#1]
To be able to use the workbook (edge-workbook.json) in Azure Monitor for IoT Edge > 1.0.9 you'll need to change the queries.
Search and replace **promMetrics_CL** with **IoTEdgeMetrics_CL**.

**Comment by juri33** [comment]
yes, it would be nice to update the labs docs too. Would save me a couple of hours.

**Comment by veyalla** [comment]
In the [setup steps](https://labs.iotedge.dev/codelabs/monitor-iotedge/#2) the recommended config for the sample metrics collector includes setting this:

![image](https://user-images.githubusercontent.com/22105760/92754637-e5ac8780-f33f-11ea-90ca-5e76ce9af381.png)

Was this followed?

**Comment by ReneHezser** [comment]
No, I haven't. I build the container myself and just set WorkspaceId and SharedKey.

**Comment by veyalla** [comment]
Ok, setting this per instructions will avoid this issue.
